packages:
  - 'apps/*'
  - 'libs/it-wallet'
  - 'libs/commons'
  - 'libs/env'
  - 'libs/preferences'
  - 'libs/identification'
  - 'libs/debug-info'
  - 'libs/navigation'
catalog:
  '@expo/cli': '56.1.21'
  '@react-navigation/bottom-tabs': '7.18.13'
  '@react-navigation/native': '7.3.13'
  '@react-navigation/stack': '7.10.16'
  '@testing-library/react-native': '13.3.3'
  '@types/react': '^19.2.0'
  babel-preset-expo: '~56.0.18'
  expo-crypto: '~56.0.4'
  jest-expo: '~56.0.5'
  react: '19.2.3'
  react-dom: '19.2.3'
  react-native: '0.85.3'
  react-native-safe-area-context: '~5.7.0'
  react-native-svg: '15.15.4'
  react-redux: '9.2.0'
  react-test-renderer: '19.2.3'
  serialize-error: '13.0.1'
  zod: '4.3.6'
ignoredBuiltDependencies:
  - '@swc/core'
  - 'detox'
  - 'dtrace-provider'
  - 'esbuild'
  - 'nx'
  - 'unrs-resolver'
onlyBuiltDependencies:
  - '@shopify/react-native-skia'
overrides:
  zod: '4.3.6'
patchedDependencies:
  '@pagopa/io-app-design-system': 'patches/@pagopa__io-app-design-system.patch'
  '@pagopa/io-react-native-wallet': patches/@pagopa__io-react-native-wallet.patch
