/**
 * Constants for wallet routes.
 */
const WALLET_ROUTES = {
  PID_ISSUANCE: {
    INSTANCE_CREATION: 'PID_ISSUANCE_INSTANCE_CREATION',
    ID_METHOD: 'PID_ISSUANCE_ID_METHOD',
    REQUEST: 'PID_ISSUANCE_REQUEST',
    SUCCESS: 'PID_ISSUANCE_SUCCESS',
    FAILURE: 'PID_ISSUANCE_FAILURE'
  } as const,
  PRESENTATION: {
    PID_DETAIL: 'PID_DETAIL',
    CREDENTIAL_DETAILS: 'PRESENTATION_CREDENTIAL_DETAILS',
    CREDENTIAL_CARD_MODAL: 'PRESENTATION_CREDENTIAL_CARD_MODAL',
    PRE_DEFINITION: 'PRESENTATION_PRE_DEFINITION',
    POST_DEFINITION: 'PRESENTATION_POST_DEFINITION',
    FAILURE: 'PRESENTATION_FAILURE',
    SUCCESS: 'PRESENTATION_SUCCESS'
  },
  CREDENTIAL_ISSUANCE: {
    LIST: 'CREDENTIAL_ISSUANCE_LIST',
    TRUST: 'CREDENTIAL_ISSUANCE_TRUST',
    PREVIEW: 'CREDENTIAL_ISSUANCE_PREVIEW',
    FAILURE: 'CREDENTIAL_ISSUANCE_FAILURE'
  },
  PROXIMITY: {
    PREVIEW: 'PROXIMITY_PREVIEW',
    SUCCESS: 'PROXIMITY_SUCCESS',
    FAILURE: 'PROXIMITY_FAILURE'
  }
} as const;

export default WALLET_ROUTES;
