/**
 * Constants for wallet routes.
 */
const WALLET_ROUTES = {
  PID_ISSUANCE: {
    INSTANCE_CREATION: 'PID_ISSUANCE_INSTANCE_CREATION',
    REQUEST: 'PID_ISSUANCE_REQUEST',
    SUCCESS: 'PID_ISSUANCE_SUCCESS',
    FAILURE: 'PID_ISSUANCE_FAILURE'
  } as const
} as const;

export default WALLET_ROUTES;
