/**
 * Constants for wallet routes.
 */
const WALLET_ROUTES = {
  CREDENTIAL_ISSUANCE: {
    ALREADY_OBTAINED: 'CREDENTIAL_ISSUANCE_ALREADY_OBTAINED',
    FAILURE: 'CREDENTIAL_ISSUANCE_FAILURE',
    LIST: 'CREDENTIAL_ISSUANCE_LIST',
    PREVIEW: 'CREDENTIAL_ISSUANCE_PREVIEW',
    TRUST: 'CREDENTIAL_ISSUANCE_TRUST'
  },
  // Landing for credential offer (OID4VCI) deep links / QR codes: resolves the
  // offer and starts the credential issuance flow.
  CREDENTIAL_OFFER: {
    ISSUANCE: 'CREDENTIAL_OFFER_ISSUANCE'
  },
  // Centralized deep link / QR entry point which inspects the incoming URL
  // scheme and dispatches to the appropriate flow.
  DEEP_LINK: {
    ERROR: 'DEEP_LINK_ERROR',
    HANDLER: 'DEEP_LINK_HANDLER'
  },
  PRESENTATION: {
    CREDENTIAL_DETAILS: 'PRESENTATION_CREDENTIAL_DETAILS',
    CREDENTIAL_NOT_FOUND: 'PRESENTATION_CREDENTIAL_NOT_FOUND',
    FAILURE: 'PRESENTATION_FAILURE',
    POST_DEFINITION: 'PRESENTATION_POST_DEFINITION',
    PRE_DEFINITION: 'PRESENTATION_PRE_DEFINITION',
    SUCCESS: 'PRESENTATION_SUCCESS',
    WALLET_NOT_ACTIVE: 'PRESENTATION_WALLET_NOT_ACTIVE'
  },
  PROXIMITY: {
    FAILURE: 'PROXIMITY_FAILURE',
    PREVIEW: 'PROXIMITY_PREVIEW',
    STORE_CONSENT: 'PROXIMITY_STORE_CONSENT',
    SUCCESS: 'PROXIMITY_SUCCESS'
  }
} as const;

export default WALLET_ROUTES;
