/**
 * Routes definition for {@link MainStackNavigator}.
 */
const MAIN_ROUTES = {
  // Main section
  TAB_NAV: 'MAIN_TAB_NAV',
  WALLET_NAV: 'MAIN_WALLET_NAV',
  SETTINGS: {
    MAIN: 'MAIN_SETTINGS',
    PREFERENCES: {
      MAIN: 'MAIN_SETTINGS_PREFERENCES',
      APPEARANCE: 'MAIN_SETTINGS_PREFERENCES_APPEARANCE'
    },
    PROXIMITY: 'MAIN_SETTINGS_PROXIMITY'
  },
  SCAN_QR: 'MAIN_SCAN_QR',
  BLE_PRESENTMENT: 'MAIN_BLE_PRESENTMENT',
  NFC_PRESENTMENT: 'MAIN_NFC_PRESENTMENT',
  // Hardware gates for the proximity presentation
  PROXIMITY_BLUETOOTH_PERMISSIONS: 'MAIN_PROXIMITY_BLUETOOTH_PERMISSIONS',
  PROXIMITY_BLUETOOTH_ACTIVATION: 'MAIN_PROXIMITY_BLUETOOTH_ACTIVATION',
  PROXIMITY_NFC_ACTIVATION: 'MAIN_PROXIMITY_NFC_ACTIVATION'
} as const;

export default MAIN_ROUTES;
