/**
 * Constants for wallet routes.
 */
const WALLET_ROUTES = {
  // Centralized deep link / QR entry point which inspects the incoming URL
  // scheme and dispatches to the appropriate flow.
  DEEP_LINK: {
    HANDLER: 'DEEP_LINK_HANDLER',
    ERROR: 'DEEP_LINK_ERROR'
  },
  // Landing for credential offer (OID4VCI) deep links / QR codes: resolves the
  // offer and starts the credential issuance flow.
  CREDENTIAL_OFFER: {
    ISSUANCE: 'CREDENTIAL_OFFER_ISSUANCE'
  },
  PID_ISSUANCE: {
    INSTANCE_CREATION: 'PID_ISSUANCE_INSTANCE_CREATION',
    ID_METHOD: 'PID_ISSUANCE_ID_METHOD',
    REQUEST: 'PID_ISSUANCE_REQUEST',
    FAILURE: 'PID_ISSUANCE_FAILURE'
  } as const,
  PRESENTATION: {
    PID_DETAIL: 'PID_DETAIL',
    CREDENTIAL_DETAILS: 'PRESENTATION_CREDENTIAL_DETAILS',
    CREDENTIAL_CARD_MODAL: 'PRESENTATION_CREDENTIAL_CARD_MODAL',
    PRE_DEFINITION: 'PRESENTATION_PRE_DEFINITION',
    POST_DEFINITION: 'PRESENTATION_POST_DEFINITION',
    FAILURE: 'PRESENTATION_FAILURE',
    CREDENTIAL_NOT_FOUND: 'PRESENTATION_CREDENTIAL_NOT_FOUND',
    WALLET_NOT_ACTIVE: 'PRESENTATION_WALLET_NOT_ACTIVE',
    SUCCESS: 'PRESENTATION_SUCCESS'
  },
  CREDENTIAL_ISSUANCE: {
    LIST: 'CREDENTIAL_ISSUANCE_LIST',
    TRUST: 'CREDENTIAL_ISSUANCE_TRUST',
    PREVIEW: 'CREDENTIAL_ISSUANCE_PREVIEW',
    FAILURE: 'CREDENTIAL_ISSUANCE_FAILURE',
    ALREADY_OBTAINED: 'CREDENTIAL_ISSUANCE_ALREADY_OBTAINED'
  },
  PROXIMITY: {
    PREVIEW: 'PROXIMITY_PREVIEW',
    SUCCESS: 'PROXIMITY_SUCCESS',
    FAILURE: 'PROXIMITY_FAILURE'
  }
} as const;

export default WALLET_ROUTES;
