# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

platform :android do
  desc "Build the App in release mode"
  lane :build_release do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "android/"
    )
  end

  desc "Bump app version"
  lane :bump_version do |options|
     android_set_version_name(
      version_name: "#{ENV['NEW_APP_VERSION']}",
      gradle_file: "android/app/build.gradle"
    )
    android_set_version_code(
      gradle_file: "android/app/build.gradle"
    )
  end

  desc "Build the App in release mode and deploy in alpha track on the Google Play Store"
  lane :alpha_playstore do |options|
    build_release

    # Generate the changelog from the last commit message
    changelog_from_git_commits(
      commits_count: 1
    )

    upload_to_play_store(
      track: "internal",
      # This must be enabled only when the app is only published in the internal test track. 
      # Once the app is published at least once in other track, this can be removed or set to false.
      # release_status: "draft",
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end

  desc "Download universal APK file from Google Play"
  lane :download_apk do
    version_code = ENV['VERSION_CODE'].to_i
    download_universal_apk_from_google_play(
      package_name: "it.pagopa.io.app.poc.eudiw",
      destination: "io-eudiw-app-universal.apk",
      version_code: version_code
    )
  end
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(type: 'appstore')
  end

  desc "Bump app version"
  lane :bump_version do |options|
    # Increment the version number based on the bump_type parameter
    increment_version_number(
      version_number: "#{ENV['NEW_APP_VERSION']}",
      xcodeproj: "ios/ioeudiw.xcodeproj"
    )

    # increment the build number 
    increment_build_number(xcodeproj: "ios/ioeudiw.xcodeproj")
  end
  
  desc "Submit a new beta build to TestFlight"
  lane :beta_testflight do |options|

    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'false'

    # Setup the CI environment
    setup_ci()

    # use the App Store API Key to authenticate
    api_key = app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_API_KEY_ID']}",
      issuer_id: "#{ENV['APP_STORE_API_KEY_ISSUER_ID']}",
      key_filepath: "./fastlane/AuthKey_#{ENV['APP_STORE_API_KEY_ID']}.p8",
      duration: 1200,
    )

    sync_code_signing(type: "appstore", app_identifier:"it.pagopa.app.io.poc.eudiw", api_key: api_key)

    # Install pods
    cocoapods(podfile: "ios/Podfile")

    # Temporary disables automatic code signing to avoid issues during build
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/ioeudiw.xcodeproj",
      team_id: "M2X5YQ4BJ7",
      profile_name: "match AppStore it.pagopa.app.io.poc.eudiw",
      targets: ["ioeudiw"],
      build_configurations: ["Release"],
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
    )

    # build the app
    gym(
      scheme: "ioeudiw",
      clean: true,
      export_method: "app-store",
      workspace: "ios/ioeudiw.xcworkspace",
      include_symbols: false
    )

    # upload to App store
    pilot(
      api_key: api_key,
      # max wait for App Store Connect processing (30 min)
      wait_processing_timeout_duration: 1800
    )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer