import { ITW_ROUTES } from "./ItwRoutes";

export type ItwParamsList = {
  [ITW_ROUTES.MAIN]: undefined;

  // ISSUANCE PID
  [ITW_ROUTES.ISSUANCE.PID.INFO]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.AUTH]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.AUTH_INFO]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.REQUEST]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.PREVIEW]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.STORE]: undefined;

  // ISSUANCE PID CIE
  [ITW_ROUTES.ISSUANCE.PID.CIE.EXPIRED_SCREEN]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.CIE.PIN_SCREEN]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.CIE.CARD_READER_SCREEN]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.CIE.CONSENT_DATA_USAGE]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.CIE.WRONG_PIN_SCREEN]: undefined;
  [ITW_ROUTES.ISSUANCE.PID.CIE.PIN_TEMP_LOCKED_SCREEN]: undefined;

  // ISSUANCE CREDENTIALS
  [ITW_ROUTES.ISSUANCE.CREDENTIAL.CATALOG]: undefined;
  [ITW_ROUTES.ISSUANCE.CREDENTIAL.CHECKS]: undefined;
  [ITW_ROUTES.ISSUANCE.CREDENTIAL.AUTH]: undefined;
  [ITW_ROUTES.ISSUANCE.CREDENTIAL.PREVIEW]: undefined;

  // PRESENTATION REMOTE PID
  [ITW_ROUTES.PRESENTATION.PID.DETAILS]: undefined;
  [ITW_ROUTES.PRESENTATION.PID.REMOTE.INIT]: undefined;
  [ITW_ROUTES.PRESENTATION.PID.REMOTE.DATA]: undefined;
  [ITW_ROUTES.PRESENTATION.PID.REMOTE.RESULT]: undefined;

  // PRESENTATION REMOTE CREDENTIAL
  [ITW_ROUTES.PRESENTATION.CREDENTIAL.DETAILS]: undefined;
  [ITW_ROUTES.PRESENTATION.CREDENTIAL.REMOTE.INIT]: undefined;
  [ITW_ROUTES.PRESENTATION.CREDENTIAL.REMOTE.DATA]: undefined;
  [ITW_ROUTES.PRESENTATION.CREDENTIAL.REMOTE.RESULT]: undefined;

  // PRESENTATION PROXIMITY
  [ITW_ROUTES.PRESENTATION.PROXIMITY.QRCODE]: undefined;

  // GENERIC
  [ITW_ROUTES.GENERIC.NOT_AVAILABLE]: undefined;
};
