/**
 * Routes configuration for the {@link OnBoardingNavigator.tsx}
 */
const ONBOARDING_ROUTES = {
  BIOMETRIC: {
    AVAILABLE: 'ONBOARDING_BIOMETRIC_AVAILABLE',
    NO_SCREEN_LOCK: 'ONBOARDING_BIOMETRIC_NO_SCREEN_LOCK',
    NOT_ENROLLED: 'ONBOARDING_BIOMETRIC_NOT_ENROLLED'
  },
  CAROUSEL: 'ONBOARDING_CAROUSEL',
  // Onboarding section
  MAIN: 'ONBOARDING_MAIN',
  PIN: {
    CREATION: 'ONBOARDING_PIN_CREATION'
  },
  START: 'ONBOARDING_START'
} as const;

export default ONBOARDING_ROUTES;
