source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.3.6"

#Fastlane 
gem "fastlane", "~> 2.233.1"

#CocoaPods
gem 'cocoapods', '>= 1.13', '!= 1.15.1', '!= 1.15.0'
