# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(type: 'appstore')
  end

  desc "Bump app version"
  lane :bump_version do |options|
    # Increment the version number based on the bump_type parameter
    increment_version_number(
      version_number: "#{ENV['NEW_APP_VERSION']}",
      xcodeproj: "ios/IoEudiwApp.xcodeproj"
    )

    # increment the build number 
    increment_build_number(xcodeproj: "ios/IoEudiwApp.xcodeproj")
  end
  
  desc "Submit a new beta build to TestFlight"
  lane :beta_testflight do |options|

    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'false'

    # Setup the CI environment
    setup_ci()

    # use the App Store API Key to authenticate
    api_key = app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_API_KEY_ID']}",
      issuer_id: "#{ENV['APP_STORE_API_KEY_ISSUER_ID']}",
      key_filepath: "./fastlane/ios/AuthKey_#{ENV['APP_STORE_API_KEY_ID']}.p8",
      duration: 1200,
    )

    sync_code_signing(type: "appstore", app_identifier:"it.pagopa.app.io.poc.eudiw", api_key: api_key)

    # Install pods
    cocoapods(podfile: "ios/Podfile")

    # Temporary disables automatic code signing to avoid issues during build
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/IoEudiwApp.xcodeproj",
      team_id: "M2X5YQ4BJ7",
      profile_name: "match AppStore it.pagopa.app.io.poc.eudiw",
      targets: ["IoEudiwApp"],
      build_configurations: ["Release"],
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
    )

    # build the app
    gym(
      scheme: "IoEudiwApp",
      clean: true,
      export_method: "app-store",
      workspace: "ios/IoEudiwApp.xcworkspace",
      include_symbols: false
    )

    # upload to App store
    pilot(
      api_key: api_key,
      # max wait for App Store Connect processing (30 min)
      wait_processing_timeout_duration: 1800
    )
  end
end